
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSAND ASSIGN COMMA DIVIDE DOT ELSE END EQUAL EXEC FALSE FUNC GREATERTHAN IDENTIFIER IF IN LBRACE LESSTHAN LET LPAREN MINUS NIL NUMBER OR PLUS RBRACE RPAREN STRING THEN TIMES TRUE UMINUS VALempty :stm : NUMBERstm : stm PLUS stm\n          | stm MINUS stm\n          | stm TIMES stm\n          | stm DIVIDE stm\n          | stm DOT stm \n          | stm LESSTHAN stm \n          | stm GREATERTHAN stm \n          | stm EQUAL stm \n          | stm AND stm \n          | stm OR stmstm : MINUS stm %prec UMINUSstm : STRINGstm : TRUE\n          | FALSEstm : NIL'
    
_lr_action_items = {'$end':([0,1,],[-1,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> empty","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','A2_Template.py',108),
  ('stm -> NUMBER','stm',1,'p_stm_number','A2_Template.py',112),
  ('stm -> stm PLUS stm','stm',3,'p_stm_binop','A2_Template.py',122),
  ('stm -> stm MINUS stm','stm',3,'p_stm_binop','A2_Template.py',123),
  ('stm -> stm TIMES stm','stm',3,'p_stm_binop','A2_Template.py',124),
  ('stm -> stm DIVIDE stm','stm',3,'p_stm_binop','A2_Template.py',125),
  ('stm -> stm DOT stm','stm',3,'p_stm_binop','A2_Template.py',126),
  ('stm -> stm LESSTHAN stm','stm',3,'p_stm_binop','A2_Template.py',127),
  ('stm -> stm GREATERTHAN stm','stm',3,'p_stm_binop','A2_Template.py',128),
  ('stm -> stm EQUAL stm','stm',3,'p_stm_binop','A2_Template.py',129),
  ('stm -> stm AND stm','stm',3,'p_stm_binop','A2_Template.py',130),
  ('stm -> stm OR stm','stm',3,'p_stm_binop','A2_Template.py',131),
  ('stm -> MINUS stm','stm',2,'p_stm_uminus','A2_Template.py',135),
  ('stm -> STRING','stm',1,'p_stm_string','A2_Template.py',139),
  ('stm -> TRUE','stm',1,'p_stm_bool','A2_Template.py',143),
  ('stm -> FALSE','stm',1,'p_stm_bool','A2_Template.py',144),
  ('stm -> NIL','stm',1,'p_stm_nil','A2_Template.py',148),
]
